/* ANSI-C code produced by gperf version 3.0.4 */
/* Command-line: /usr/bin/gperf -L ANSI-C -t --ignore-case -N lookup_key -H hash_key_name -p -C  */
/* Computed positions: -k'5-8,15,20,$' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

struct key { const char* name; unsigned short id; };

#define TOTAL_KEYWORDS 416
#define MIN_WORD_LENGTH 5
#define MAX_WORD_LENGTH 28
#define MIN_HASH_VALUE 5
#define MAX_HASH_VALUE 1427
/* maximum key range = 1423, duplicates = 0 */

#ifndef GPERF_DOWNCASE
#define GPERF_DOWNCASE 1
static unsigned char gperf_downcase[256] =
  {
      0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
     15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
     30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,
     45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,
     60,  61,  62,  63,  64,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106,
    107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
    122,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
    105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119,
    120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134,
    135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149,
    150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
    165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
    180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
    195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209,
    210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224,
    225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239,
    240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254,
    255
  };
#endif

#ifndef GPERF_CASE_STRCMP
#define GPERF_CASE_STRCMP 1
static int
gperf_case_strcmp (register const char *s1, register const char *s2)
{
  for (;;)
    {
      unsigned char c1 = gperf_downcase[(unsigned char)*s1++];
      unsigned char c2 = gperf_downcase[(unsigned char)*s2++];
      if (c1 != 0 && c1 == c2)
        continue;
      return (int)c1 - (int)c2;
    }
}
#endif

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
hash_key_name (register const char *str, register unsigned int len)
{
  static const unsigned short asso_values[] =
    {
      1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428,
      1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428,
      1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428,
      1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428,
      1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428,  245,  120,
       350,  180,  270,  400,  335,  330,  315,  285, 1428, 1428,
      1428, 1428, 1428, 1428, 1428,   10,  250,   45,  150,    5,
       370,  235,  355,  275,  145,  260,  210,   40,   75,   35,
        15,  140,   30,   25,    0,   90,  390,  340,  100,  425,
       160, 1428, 1428, 1428, 1428,  190, 1428,   10,  250,   45,
       150,    5,  370,  235,  355,  275,  145,  260,  210,   40,
        75,   35,   15,  140,   30,   25,    0,   90,  390,  340,
       100,  425,  160, 1428, 1428, 1428, 1428, 1428, 1428, 1428,
      1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428,
      1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428,
      1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428,
      1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428,
      1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428,
      1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428,
      1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428,
      1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428,
      1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428,
      1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428,
      1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428,
      1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428,
      1428, 1428, 1428, 1428, 1428, 1428
    };
  register int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[19]];
      /*FALLTHROUGH*/
      case 19:
      case 18:
      case 17:
      case 16:
      case 15:
        hval += asso_values[(unsigned char)str[14]];
      /*FALLTHROUGH*/
      case 14:
      case 13:
      case 12:
      case 11:
      case 10:
      case 9:
      case 8:
        hval += asso_values[(unsigned char)str[7]];
      /*FALLTHROUGH*/
      case 7:
        hval += asso_values[(unsigned char)str[6]];
      /*FALLTHROUGH*/
      case 6:
        hval += asso_values[(unsigned char)str[5]];
      /*FALLTHROUGH*/
      case 5:
        hval += asso_values[(unsigned char)str[4]];
        break;
    }
  return hval + asso_values[(unsigned char)str[len - 1]];
}

#ifdef __GNUC__
__inline
#if defined __GNUC_STDC_INLINE__ || defined __GNUC_GNU_INLINE__
__attribute__ ((__gnu_inline__))
#endif
#endif
const struct key *
lookup_key (register const char *str, register unsigned int len)
{
  static const struct key wordlist[] =
    {
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_T", KEY_T},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_E", KEY_E},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_A", KEY_A},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_P", KEY_P},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"KEY_SAT", KEY_SAT},
      {"KEY_TAPE", KEY_TAPE},
      {(char*)0},
      {"KEY_ATTENDANT_TOGGLE", KEY_ATTENDANT_TOGGLE},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_S", KEY_S},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_PASTE", KEY_PASTE},
      {"KEY_R", KEY_R},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_RESTART", KEY_RESTART},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_O", KEY_O},
      {(char*)0}, {(char*)0},
      {"KEY_APPSELECT", KEY_APPSELECT},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"KEY_M", KEY_M},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_SPREADSHEET", KEY_SPREADSHEET},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_C", KEY_C},
      {(char*)0}, {(char*)0},
      {"KEY_STOP", KEY_STOP},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_APOSTROPHE", KEY_APOSTROPHE},
      {(char*)0},
      {"KEY_RO", KEY_RO},
      {(char*)0}, {(char*)0},
      {"KEY_SPACE", KEY_SPACE},
      {(char*)0},
      {"KEY_PC", KEY_PC},
      {(char*)0},
      {"KEY_TEXT", KEY_TEXT},
      {"KEY_SPORT", KEY_SPORT},
      {"KEY_CAMERA_LEFT", KEY_CAMERA_LEFT},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_CAMERA", KEY_CAMERA},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_ENTER", KEY_ENTER},
      {(char*)0},
      {"KEY_UP", KEY_UP},
      {"KEY_ESC", KEY_ESC},
      {"KEY_CAMERA_UP", KEY_CAMERA_UP},
      {"KEY_PROPS", KEY_PROPS},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_MESSENGER", KEY_MESSENGER},
      {(char*)0}, {(char*)0},
      {"KEY_ATTENDANT_ON", KEY_ATTENDANT_ON},
      {"KEY_CUT", KEY_CUT},
      {(char*)0},
      {"KEY_SETUP", KEY_SETUP},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_MUTE", KEY_MUTE},
      {(char*)0}, {(char*)0},
      {"KEY_COMPOSE", KEY_COMPOSE},
      {(char*)0}, {(char*)0},
      {"KEY_PAUSE", KEY_PAUSE},
      {"KEY_N", KEY_N},
      {(char*)0}, {(char*)0},
      {"KEY_CAMERA_ZOOMOUT", KEY_CAMERA_ZOOMOUT},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_SCROLLUP", KEY_SCROLLUP},
      {"KEY_MEMO", KEY_MEMO},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_TEEN", KEY_TEEN},
      {"KEY_MACRO", KEY_MACRO},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_COMPUTER", KEY_COMPUTER},
      {(char*)0},
      {"KEY_COMMA", KEY_COMMA},
      {"KEY_SCREENSAVER", KEY_SCREENSAVER},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_U", KEY_U},
      {(char*)0},
      {"KEY_DATABASE", KEY_DATABASE},
      {"KEY_NEXT", KEY_NEXT},
      {(char*)0},
      {"KEY_SCREEN", KEY_SCREEN},
      {(char*)0},
      {"KEY_DOT", KEY_DOT},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_PRESENTATION", KEY_PRESENTATION},
      {(char*)0},
      {"KEY_EURO", KEY_EURO},
      {(char*)0},
      {"KEY_X", KEY_X},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_TUNER", KEY_TUNER},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_OPEN", KEY_OPEN},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"KEY_SCROLLDOWN", KEY_SCROLLDOWN},
      {(char*)0}, {(char*)0},
      {"KEY_RESERVED", KEY_RESERVED},
      {(char*)0},
      {"KEY_TOUCHPAD_TOGGLE", KEY_TOUCHPAD_TOGGLE},
      {(char*)0},
      {"KEY_CAMERA_FOCUS", KEY_CAMERA_FOCUS},
      {"KEY_CAMERA_ZOOMIN", KEY_CAMERA_ZOOMIN},
      {"KEY_NUMERIC_A", KEY_NUMERIC_A},
      {(char*)0},
      {"KEY_STOPCD", KEY_STOPCD},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_CONNECT", KEY_CONNECT},
      {"KEY_ALTERASE", KEY_ALTERASE},
      {"KEY_MODE", KEY_MODE},
      {(char*)0},
      {"KEY_1", KEY_1},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_LAST", KEY_LAST},
      {(char*)0},
      {"KEY_SELECT", KEY_SELECT},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_REDO", KEY_REDO},
      {(char*)0},
      {"KEY_CAMERA_DOWN", KEY_CAMERA_DOWN},
      {"KEY_NUMERIC_STAR", KEY_NUMERIC_STAR},
      {(char*)0},
      {"KEY_NUMERIC_C", KEY_NUMERIC_C},
      {"KEY_SLEEP", KEY_SLEEP},
      {(char*)0}, {(char*)0},
      {"KEY_SENDFILE", KEY_SENDFILE},
      {(char*)0}, {(char*)0},
      {"KEY_RECORD", KEY_RECORD},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_ZOOMOUT", KEY_ZOOMOUT},
      {(char*)0},
      {"KEY_ZOOMRESET", KEY_ZOOMRESET},
      {"KEY_MSDOS", KEY_MSDOS},
      {"KEY_Q", KEY_Q},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_PAGEUP", KEY_PAGEUP},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_J", KEY_J},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_PAUSECD", KEY_PAUSECD},
      {"KEY_KATAKANA", KEY_KATAKANA},
      {(char*)0},
      {"KEY_SCALE", KEY_SCALE},
      {"KEY_D", KEY_D},
      {(char*)0},
      {"KEY_AUX", KEY_AUX},
      {"KEY_MENU", KEY_MENU},
      {"KEY_CLEAR", KEY_CLEAR},
      {(char*)0}, {(char*)0},
      {"KEY_CALENDAR", KEY_CALENDAR},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_SUSPEND", KEY_SUSPEND},
      {(char*)0},
      {"KEY_ZOOM", KEY_ZOOM},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_BASSBOOST", KEY_BASSBOOST},
      {"KEY_GAMES", KEY_GAMES},
      {"KEY_Z", KEY_Z},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_CLOSE", KEY_CLOSE},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_TIME", KEY_TIME},
      {(char*)0},
      {"KEY_TOUCHPAD_ON", KEY_TOUCHPAD_ON},
      {"KEY_CONTEXT_MENU", KEY_CONTEXT_MENU},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_RED", KEY_RED},
      {"KEY_NUMERIC_1", KEY_NUMERIC_1},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_QUESTION", KEY_QUESTION},
      {"KEY_GOTO", KEY_GOTO},
      {(char*)0},
      {"KEY_KATAKANAHIRAGANA", KEY_KATAKANAHIRAGANA},
      {"KEY_CD", KEY_CD},
      {"KEY_PAGEDOWN", KEY_PAGEDOWN},
      {(char*)0}, {(char*)0},
      {"KEY_ZOOMIN", KEY_ZOOMIN},
      {(char*)0}, {(char*)0},
      {"KEY_DOCUMENTS", KEY_DOCUMENTS},
      {"KEY_GREEN", KEY_GREEN},
      {(char*)0},
      {"KEY_EJECTCD", KEY_EJECTCD},
      {(char*)0},
      {"KEY_CALC", KEY_CALC},
      {(char*)0},
      {"KEY_3", KEY_3},
      {"KEY_PROGRAM", KEY_PROGRAM},
      {"KEY_CAPSLOCK", KEY_CAPSLOCK},
      {(char*)0}, {(char*)0},
      {"KEY_TASKMANAGER", KEY_TASKMANAGER},
      {(char*)0}, {(char*)0},
      {"KEY_NUMERIC_D", KEY_NUMERIC_D},
      {(char*)0}, {(char*)0},
      {"KEY_KPCOMMA", KEY_KPCOMMA},
      {"KEY_ISO", KEY_ISO},
      {(char*)0},
      {"KEY_SCREENLOCK", KEY_SCREENLOCK},
      {(char*)0}, {(char*)0},
      {"KEY_SUBTITLE", KEY_SUBTITLE},
      {(char*)0},
      {"KEY_SOUND", KEY_SOUND},
      {"KEY_DELETE", KEY_DELETE},
      {"KEY_CONTROLPANEL", KEY_CONTROLPANEL},
      {"KEY_END", KEY_END},
      {"KEY_EXIT", KEY_EXIT},
      {"KEY_DELETEFILE", KEY_DELETEFILE},
      {"KEY_INSERT", KEY_INSERT},
      {"KEY_HP", KEY_HP},
      {(char*)0},
      {"KEY_UNDO", KEY_UNDO},
      {(char*)0},
      {"KEY_CANCEL", KEY_CANCEL},
      {"KEY_KPENTER", KEY_KPENTER},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"KEY_NUMERIC_3", KEY_NUMERIC_3},
      {"KEY_PRINT", KEY_PRINT},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_SCROLLLOCK", KEY_SCROLLLOCK},
      {"KEY_OPTION", KEY_OPTION},
      {"KEY_EJECTCLOSECD", KEY_EJECTCLOSECD},
      {(char*)0},
      {"KEY_SEND", KEY_SEND},
      {(char*)0}, {(char*)0},
      {"KEY_MICMUTE", KEY_MICMUTE},
      {(char*)0},
      {"KEY_CHAT", KEY_CHAT},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_MP3", KEY_MP3},
      {(char*)0}, {(char*)0},
      {"KEY_L", KEY_L},
      {(char*)0},
      {"KEY_NEXTSONG", KEY_NEXTSONG},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_MHP", KEY_MHP},
      {"KEY_SEMICOLON", KEY_SEMICOLON},
      {"KEY_POWER", KEY_POWER},
      {"KEY_SEARCH", KEY_SEARCH},
      {(char*)0},
      {"KEY_ATTENDANT_OFF", KEY_ATTENDANT_OFF},
      {"KEY_EDIT", KEY_EDIT},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_SAVE", KEY_SAVE},
      {"KEY_PROG1", KEY_PROG1},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_HOME", KEY_HOME},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_HOMEPAGE", KEY_HOMEPAGE},
      {"KEY_SHOP", KEY_SHOP},
      {"KEY_ALS_TOGGLE", KEY_ALS_TOGGLE},
      {(char*)0},
      {"KEY_ARCHIVE", KEY_ARCHIVE},
      {(char*)0},
      {"KEY_KPJPCOMMA", KEY_KPJPCOMMA},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_EQUAL", KEY_EQUAL},
      {(char*)0}, {(char*)0},
      {"KEY_NUMERIC_POUND", KEY_NUMERIC_POUND},
      {"KEY_NUMERIC_0", KEY_NUMERIC_0},
      {"KEY_KPDOT", KEY_KPDOT},
      {"KEY_EDITOR", KEY_EDITOR},
      {"KEY_CAMERA_RIGHT", KEY_CAMERA_RIGHT},
      {"KEY_PVR", KEY_PVR},
      {"KEY_NUMERIC_B", KEY_NUMERIC_B},
      {(char*)0},
      {"KEY_G", KEY_G},
      {"KEY_CLOSECD", KEY_CLOSECD},
      {"KEY_PREVIOUS", KEY_PREVIOUS},
      {"KEY_NEWS", KEY_NEWS},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_MOVE", KEY_MOVE},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_MEDIA", KEY_MEDIA},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_NUMERIC_4", KEY_NUMERIC_4},
      {"KEY_PHONE", KEY_PHONE},
      {"KEY_0", KEY_0},
      {"KEY_MEDIA_REPEAT", KEY_MEDIA_REPEAT},
      {"KEY_EPG", KEY_EPG},
      {(char*)0},
      {"KEY_TITLE", KEY_TITLE},
      {(char*)0}, {(char*)0},
      {"KEY_VCR", KEY_VCR},
      {"KEY_TWEN", KEY_TWEN},
      {"KEY_PROG3", KEY_PROG3},
      {"KEY_B", KEY_B},
      {(char*)0}, {(char*)0},
      {"KEY_NUMERIC_9", KEY_NUMERIC_9},
      {"KEY_RADIO", KEY_RADIO},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_CHANNELUP", KEY_CHANNELUP},
      {"KEY_MINUS", KEY_MINUS},
      {(char*)0},
      {"KEY_AB", KEY_AB},
      {"KEY_TAB", KEY_TAB},
      {"KEY_LIST", KEY_LIST},
      {"KEY_FRONT", KEY_FRONT},
      {(char*)0},
      {"KEY_JOURNAL", KEY_JOURNAL},
      {"KEY_KP1", KEY_KP1},
      {(char*)0}, {(char*)0},
      {"KEY_K", KEY_K},
      {"KEY_FN", KEY_FN},
      {(char*)0}, {(char*)0},
      {"KEY_SPELLCHECK", KEY_SPELLCHECK},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_ROTATE_DISPLAY", KEY_ROTATE_DISPLAY},
      {(char*)0},
      {"KEY_KPPLUS", KEY_KPPLUS},
      {(char*)0}, {(char*)0},
      {"KEY_NUMERIC_8", KEY_NUMERIC_8},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_XFER", KEY_XFER},
      {"KEY_ANGLE", KEY_ANGLE},
      {"KEY_4", KEY_4},
      {(char*)0},
      {"KEY_LANGUAGE", KEY_LANGUAGE},
      {(char*)0},
      {"KEY_EMAIL", KEY_EMAIL},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_NUMERIC_7", KEY_NUMERIC_7},
      {(char*)0},
      {"KEY_I", KEY_I},
      {(char*)0}, {(char*)0},
      {"KEY_NUMERIC_6", KEY_NUMERIC_6},
      {(char*)0}, {(char*)0},
      {"KEY_OK", KEY_OK},
      {(char*)0}, {(char*)0},
      {"KEY_BREAK", KEY_BREAK},
      {"KEY_KPPLUSMINUS", KEY_KPPLUSMINUS},
      {(char*)0}, {(char*)0},
      {"KEY_BLUE", KEY_BLUE},
      {"KEY_AUDIO", KEY_AUDIO},
      {(char*)0}, {(char*)0},
      {"KEY_DEL_LINE", KEY_DEL_LINE},
      {"KEY_NUMERIC_2", KEY_NUMERIC_2},
      {(char*)0},
      {"KEY_9", KEY_9},
      {(char*)0},
      {"KEY_MUHENKAN", KEY_MUHENKAN},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_INS_LINE", KEY_INS_LINE},
      {"KEY_BACKSPACE", KEY_BACKSPACE},
      {"KEY_KPASTERISK", KEY_KPASTERISK},
      {(char*)0},
      {"KEY_UNKNOWN", KEY_UNKNOWN},
      {"KEY_YEN", KEY_YEN},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_DEL_EOS", KEY_DEL_EOS},
      {(char*)0},
      {"KEY_LEFT", KEY_LEFT},
      {"KEY_PROG4", KEY_PROG4},
      {"KEY_IMAGES", KEY_IMAGES},
      {"KEY_LEFTALT", KEY_LEFTALT},
      {(char*)0},
      {"KEY_LEFTSHIFT", KEY_LEFTSHIFT},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_LEFTBRACE", KEY_LEFTBRACE},
      {"KEY_HANJA", KEY_HANJA},
      {(char*)0}, {(char*)0},
      {"KEY_LEFTMETA", KEY_LEFTMETA},
      {"KEY_HELP", KEY_HELP},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_GRAPHICSEDITOR", KEY_GRAPHICSEDITOR},
      {"KEY_AGAIN", KEY_AGAIN},
      {(char*)0},
      {"KEY_F1", KEY_F1},
      {(char*)0},
      {"KEY_BOOKMARKS", KEY_BOOKMARKS},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_NUMERIC_5", KEY_NUMERIC_5},
      {(char*)0}, {(char*)0},
      {"KEY_KPMINUS", KEY_KPMINUS},
      {"KEY_WORDPROCESSOR", KEY_WORDPROCESSOR},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"KEY_SLASH", KEY_SLASH},
      {"KEY_8", KEY_8},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_WAKEUP", KEY_WAKEUP},
      {"KEY_KPEQUAL", KEY_KPEQUAL},
      {"KEY_KP3", KEY_KP3},
      {(char*)0}, {(char*)0},
      {"KEY_DOLLAR", KEY_DOLLAR},
      {"KEY_FRAMEFORWARD", KEY_FRAMEFORWARD},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_CHANNELDOWN", KEY_CHANNELDOWN},
      {(char*)0}, {(char*)0},
      {"KEY_FN_E", KEY_FN_E},
      {"KEY_SYSRQ", KEY_SYSRQ},
      {"KEY_KPLEFTPAREN", KEY_KPLEFTPAREN},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_WPS_BUTTON", KEY_WPS_BUTTON},
      {"KEY_VENDOR", KEY_VENDOR},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_7", KEY_7},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_PROG2", KEY_PROG2},
      {"KEY_6", KEY_6},
      {"KEY_KPRIGHTPAREN", KEY_KPRIGHTPAREN},
      {(char*)0},
      {"KEY_PLAYPAUSE", KEY_PLAYPAUSE},
      {"KEY_GRAVE", KEY_GRAVE},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_DOWN", KEY_DOWN},
      {(char*)0},
      {"KEY_W", KEY_W},
      {"KEY_NUMLOCK", KEY_NUMLOCK},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_HIRAGANA", KEY_HIRAGANA},
      {"KEY_FN_S", KEY_FN_S},
      {"KEY_REPLY", KEY_REPLY},
      {"KEY_FN_ESC", KEY_FN_ESC},
      {"KEY_BATTERY", KEY_BATTERY},
      {(char*)0}, {(char*)0},
      {"KEY_SWITCHVIDEOMODE", KEY_SWITCHVIDEOMODE},
      {"KEY_PLAYER", KEY_PLAYER},
      {(char*)0}, {(char*)0},
      {"KEY_DASHBOARD", KEY_DASHBOARD},
      {(char*)0},
      {"KEY_2", KEY_2},
      {"KEY_CHANNEL", KEY_CHANNEL},
      {(char*)0}, {(char*)0},
      {"KEY_FIRST", KEY_FIRST},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_H", KEY_H},
      {(char*)0}, {(char*)0},
      {"KEY_WLAN", KEY_WLAN},
      {(char*)0},
      {"KEY_FASTFORWARD", KEY_FASTFORWARD},
      {(char*)0},
      {"KEY_DISPLAYTOGGLE", KEY_DISPLAYTOGGLE},
      {"KEY_FRAMEBACK", KEY_FRAMEBACK},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_LINEFEED", KEY_LINEFEED},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_F3", KEY_F3},
      {"KEY_F11", KEY_F11},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_SAT2", KEY_SAT2},
      {(char*)0},
      {"KEY_F", KEY_F},
      {"KEY_FINANCE", KEY_FINANCE},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_VOLUMEUP", KEY_VOLUMEUP},
      {"KEY_MAIL", KEY_MAIL},
      {(char*)0},
      {"KEY_POWER2", KEY_POWER2},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"KEY_PREVIOUSSONG", KEY_PREVIOUSSONG},
      {"KEY_NEW", KEY_NEW},
      {(char*)0}, {(char*)0},
      {"KEY_CONFIG", KEY_CONFIG},
      {(char*)0},
      {"KEY_KP0", KEY_KP0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_DEL_EOL", KEY_DEL_EOL},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_HENKAN", KEY_HENKAN},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_V", KEY_V},
      {"KEY_TV", KEY_TV},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_INFO", KEY_INFO},
      {(char*)0}, {(char*)0},
      {"KEY_REFRESH", KEY_REFRESH},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_5", KEY_5},
      {(char*)0},
      {"KEY_LEFTCTRL", KEY_LEFTCTRL},
      {(char*)0}, {(char*)0},
      {"KEY_REWIND", KEY_REWIND},
      {(char*)0},
      {"KEY_BRL_DOT1", KEY_BRL_DOT1},
      {(char*)0},
      {"KEY_VOLUMEDOWN", KEY_VOLUMEDOWN},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_PLAYCD", KEY_PLAYCD},
      {(char*)0},
      {"KEY_KP4", KEY_KP4},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"KEY_BACK", KEY_BACK},
      {"KEY_VIDEO_NEXT", KEY_VIDEO_NEXT},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_VIDEOPHONE", KEY_VIDEOPHONE},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_FAVORITES", KEY_FAVORITES},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_DVD", KEY_DVD},
      {"KEY_WWAN", KEY_WWAN},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_KP9", KEY_KP9},
      {(char*)0}, {(char*)0},
      {"KEY_Y", KEY_Y},
      {"KEY_SHUFFLE", KEY_SHUFFLE},
      {"KEY_F13", KEY_F13},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"KEY_VIDEO", KEY_VIDEO},
      {(char*)0},
      {"KEY_BUTTONCONFIG", KEY_BUTTONCONFIG},
      {(char*)0},
      {"KEY_ZENKAKUHANKAKU", KEY_ZENKAKUHANKAKU},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_BRL_DOT3", KEY_BRL_DOT3},
      {"KEY_FILE", KEY_FILE},
      {(char*)0},
      {"KEY_ADDRESSBOOK", KEY_ADDRESSBOOK},
      {"KEY_KPSLASH", KEY_KPSLASH},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"KEY_FN_1", KEY_FN_1},
      {(char*)0}, {(char*)0},
      {"KEY_10CHANNELSUP", KEY_10CHANNELSUP},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_LOGOFF", KEY_LOGOFF},
      {"KEY_HANGEUL", KEY_HANGEUL},
      {(char*)0},
      {"KEY_DIRECTORY", KEY_DIRECTORY},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_RIGHT", KEY_RIGHT},
      {(char*)0}, {(char*)0},
      {"KEY_RIGHTALT", KEY_RIGHTALT},
      {(char*)0},
      {"KEY_RIGHTSHIFT", KEY_RIGHTSHIFT},
      {(char*)0},
      {"KEY_BRIGHTNESSUP", KEY_BRIGHTNESSUP},
      {"KEY_KP8", KEY_KP8},
      {(char*)0},
      {"KEY_RIGHTBRACE", KEY_RIGHTBRACE},
      {(char*)0},
      {"KEY_F4", KEY_F4},
      {(char*)0},
      {"KEY_RIGHTMETA", KEY_RIGHTMETA},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_BLUETOOTH", KEY_BLUETOOTH},
      {(char*)0}, {(char*)0},
      {"KEY_TOUCHPAD_OFF", KEY_TOUCHPAD_OFF},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"KEY_BACKSLASH", KEY_BACKSLASH},
      {(char*)0}, {(char*)0},
      {"KEY_FORWARD", KEY_FORWARD},
      {"KEY_UWB", KEY_UWB},
      {"KEY_BRL_DOT10", KEY_BRL_DOT10},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_KP7", KEY_KP7},
      {"KEY_FN_D", KEY_FN_D},
      {(char*)0}, {(char*)0},
      {"KEY_F9", KEY_F9},
      {(char*)0}, {(char*)0},
      {"KEY_102ND", KEY_102ND},
      {(char*)0}, {(char*)0},
      {"KEY_KP6", KEY_KP6},
      {"KEY_COPY", KEY_COPY},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_SLOW", KEY_SLOW},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_BRL_DOT4", KEY_BRL_DOT4},
      {(char*)0},
      {"KEY_KBDILLUMUP", KEY_KBDILLUMUP},
      {(char*)0}, {(char*)0},
      {"KEY_F21", KEY_F21},
      {"KEY_VOICEMAIL", KEY_VOICEMAIL},
      {(char*)0},
      {"KEY_DIGITS", KEY_DIGITS},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"KEY_BRL_DOT9", KEY_BRL_DOT9},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_KP2", KEY_KP2},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_VOICECOMMAND", KEY_VOICECOMMAND},
      {"KEY_F10", KEY_F10},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_KBDINPUTASSIST_ACCEPT", KEY_KBDINPUTASSIST_ACCEPT},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"KEY_F8", KEY_F8},
      {"KEY_BRL_DOT8", KEY_BRL_DOT8},
      {"KEY_10CHANNELSDOWN", KEY_10CHANNELSDOWN},
      {(char*)0},
      {"KEY_BRIGHTNESS_CYCLE", KEY_BRIGHTNESS_CYCLE},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_KBDINPUTASSIST_PREVGROUP", KEY_KBDINPUTASSIST_PREVGROUP},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_BRL_DOT7", KEY_BRL_DOT7},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_BRL_DOT6", KEY_BRL_DOT6},
      {"KEY_FIND", KEY_FIND},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_BRIGHTNESSDOWN", KEY_BRIGHTNESSDOWN},
      {"KEY_BRIGHTNESS_AUTO", KEY_BRIGHTNESS_AUTO},
      {(char*)0},
      {"KEY_F7", KEY_F7},
      {"KEY_F14", KEY_F14},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_BRL_DOT2", KEY_BRL_DOT2},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_F6", KEY_F6},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_KBDINPUTASSIST_NEXT", KEY_KBDINPUTASSIST_NEXT},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_F19", KEY_F19},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_BRIGHTNESS_MIN", KEY_BRIGHTNESS_MIN},
      {(char*)0}, {(char*)0},
      {"KEY_F2", KEY_F2},
      {(char*)0},
      {"KEY_KBDINPUTASSIST_NEXTGROUP", KEY_KBDINPUTASSIST_NEXTGROUP},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_KP5", KEY_KP5},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_F23", KEY_F23},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_BRL_DOT5", KEY_BRL_DOT5},
      {"KEY_PLAY", KEY_PLAY},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_TV2", KEY_TV2},
      {"KEY_BRIGHTNESS_MAX", KEY_BRIGHTNESS_MAX},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_KEYBOARD", KEY_KEYBOARD},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_CYCLEWINDOWS", KEY_CYCLEWINDOWS},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_RIGHTCTRL", KEY_RIGHTCTRL},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_F18", KEY_F18},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"KEY_FN_F1", KEY_FN_F1},
      {"KEY_FN_F11", KEY_FN_F11},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_FN_B", KEY_FN_B},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_RFKILL", KEY_RFKILL},
      {(char*)0},
      {"KEY_F17", KEY_F17},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_F16", KEY_F16},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_VCR2", KEY_VCR2},
      {(char*)0}, {(char*)0},
      {"KEY_F5", KEY_F5},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_KBDILLUMTOGGLE", KEY_KBDILLUMTOGGLE},
      {"KEY_FN_F3", KEY_FN_F3},
      {(char*)0}, {(char*)0},
      {"KEY_F12", KEY_F12},
      {(char*)0}, {(char*)0},
      {"KEY_YELLOW", KEY_YELLOW},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_FORWARDMAIL", KEY_FORWARDMAIL},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"KEY_F20", KEY_F20},
      {(char*)0}, {(char*)0},
      {"KEY_DISPLAY_OFF", KEY_DISPLAY_OFF},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_VIDEO_PREV", KEY_VIDEO_PREV},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_KBDINPUTASSIST_CANCEL", KEY_KBDINPUTASSIST_CANCEL},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_FN_F10", KEY_FN_F10},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"KEY_F24", KEY_F24},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_FN_F4", KEY_FN_F4},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_F15", KEY_F15},
      {(char*)0},
      {"KEY_FN_F9", KEY_FN_F9},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_FN_F8", KEY_FN_F8},
      {(char*)0}, {(char*)0},
      {"KEY_LIGHTS_TOGGLE", KEY_LIGHTS_TOGGLE},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"KEY_FN_2", KEY_FN_2},
      {"KEY_FN_F7", KEY_FN_F7},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_FN_F6", KEY_FN_F6},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"KEY_FN_F2", KEY_FN_F2},
      {"KEY_FN_F12", KEY_FN_F12},
      {"KEY_KBDILLUMDOWN", KEY_KBDILLUMDOWN},
      {"KEY_WWW", KEY_WWW},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_FN_F", KEY_FN_F},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_KBDINPUTASSIST_PREV", KEY_KBDINPUTASSIST_PREV},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"KEY_FN_F5", KEY_FN_F5},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"KEY_F22", KEY_F22}
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = hash_key_name (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        {
          register const char *s = wordlist[key].name;

          if (s && (((unsigned char)*str ^ (unsigned char)*s) & ~32) == 0 && !gperf_case_strcmp (str, s))
            return &wordlist[key];
        }
    }
  return 0;
}
