/* ANSI-C code produced by gperf version 3.0.4 */
/* Command-line: /usr/bin/gperf  */
/* Computed positions: -k'3,9,12,15,$' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif


#include <stddef.h>
#include "conf-parser.h"
#include "load-fragment.h"
#include "missing.h"
#include <string.h>

#define TOTAL_KEYWORDS 440
#define MIN_WORD_LENGTH 9
#define MAX_WORD_LENGTH 32
#define MIN_HASH_VALUE 24
#define MAX_HASH_VALUE 1650
/* maximum key range = 1627, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
load_fragment_gperf_hash (register const char *str, register unsigned int len)
{
  static const unsigned short asso_values[] =
    {
      1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651,
      1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651,
      1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651,
      1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651,
      1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651,
      1651, 1651, 1651, 1651,    0, 1651, 1651, 1651, 1651, 1651,
      1651, 1651, 1651, 1651, 1651,  475,  145,  125,  365,  340,
       475,  145,   10,  145, 1651,  185,  215,  425,  435,  405,
       255,   15,  195,   75,  310,  350,  150,  285, 1651,  100,
         0, 1651, 1651, 1651, 1651, 1651, 1651,   25,  110,   10,
        30,    0,  325,  120,  225,    5, 1651,  430,   95,  290,
        55,   15,  220, 1651,   15,   55,    5,   30,   55,   55,
       190,  160, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651,
      1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651,
      1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651,
      1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651,
      1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651,
      1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651,
      1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651,
      1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651,
      1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651,
      1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651,
      1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651,
      1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651,
      1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651, 1651,
      1651, 1651, 1651, 1651, 1651, 1651
    };
  register int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[14]];
      /*FALLTHROUGH*/
      case 14:
      case 13:
      case 12:
        hval += asso_values[(unsigned char)str[11]];
      /*FALLTHROUGH*/
      case 11:
      case 10:
      case 9:
        hval += asso_values[(unsigned char)str[8]];
      /*FALLTHROUGH*/
      case 8:
      case 7:
      case 6:
      case 5:
      case 4:
      case 3:
        hval += asso_values[(unsigned char)str[2]];
        break;
    }
  return hval + asso_values[(unsigned char)str[len - 1]];
}

#ifdef __GNUC__
__inline
#if defined __GNUC_STDC_INLINE__ || defined __GNUC_GNU_INLINE__
__attribute__ ((__gnu_inline__))
#endif
#endif
const struct ConfigPerfItem *
load_fragment_gperf_lookup (register const char *str, register unsigned int len)
{
  static const struct ConfigPerfItem wordlist[] =
    {
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"Path.Unit",                       config_parse_trigger_unit,          0,                             0},
      {(char*)0},
      {"Socket.Nice",                         config_parse_exec_nice,             0,                             offsetof(Socket, exec_context)},
      {(char*)0}, {(char*)0},
      {"Socket.Service",                  config_parse_socket_service,        0,                             0},
      {"Unit.After",                      config_parse_unit_deps,             UNIT_AFTER,                    0},
      {"Unit.Before",                     config_parse_unit_deps,             UNIT_BEFORE,                   0},
      {(char*)0}, {(char*)0},
      {"Swap.Nice",                         config_parse_exec_nice,             0,                             offsetof(Swap, exec_context)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"Socket.ListenMessageQueue",       config_parse_socket_listen,         SOCKET_MQUEUE,                 0},
      {"Mount.Where",                     config_parse_path,                  0,                             offsetof(Mount, where)},
      {(char*)0}, {(char*)0},
      {"Swap.What",                       config_parse_path,                  0,                             offsetof(Swap, parameters_fragment.what)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Automount.DirectoryMode",         config_parse_mode,                  0,                             offsetof(Automount, directory_mode)},
      {"Socket.ListenSequentialPacket",   config_parse_socket_listen,         SOCKET_SOCKET,                 0},
      {"Mount.Nice",                         config_parse_exec_nice,             0,                             offsetof(Mount, exec_context)},
      {(char*)0}, {(char*)0},
      {"Socket.MemoryLimit",                  config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {"Unit.Requisite",                  config_parse_unit_deps,             UNIT_REQUISITE,                0},
      {"Mount.User",                         config_parse_unit_string_printf,    0,                             offsetof(Mount, exec_context.user)},
      {(char*)0},
      {"Socket.SocketMode",               config_parse_mode,                  0,                             offsetof(Socket, socket_mode)},
      {(char*)0}, {(char*)0},
      {"Socket.DirectoryMode",            config_parse_mode,                  0,                             offsetof(Socket, directory_mode)},
      {"Unit.BindTo",                     config_parse_unit_deps,             UNIT_BINDS_TO,                 0},
      {(char*)0}, {(char*)0},
      {"Swap.User",                         config_parse_unit_string_printf,    0,                             offsetof(Swap, exec_context.user)},
      {"Swap.TimeoutSec",                 config_parse_sec,                   0,                             offsetof(Swap, timeout_usec)},
      {(char*)0},
      {"Socket.MemorySoftLimit",              config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {(char*)0}, {(char*)0},
      {"Mount.What",                      config_parse_string,                0,                             offsetof(Mount, parameters_fragment.what)},
      {(char*)0}, {(char*)0},
      {"Unit.ConditionHost",              config_parse_unit_condition_string, CONDITION_HOST,                0},
      {"Unit.OnFailure",                  config_parse_unit_deps,             UNIT_ON_FAILURE,               0},
      {"Unit.Wants",                      config_parse_unit_deps,             UNIT_WANTS,                    0},
      {(char*)0},
      {"Unit.BindsTo",                    config_parse_unit_deps,             UNIT_BINDS_TO,                 0},
      {(char*)0}, {(char*)0},
      {"Socket.MessageQueueMessageSize",  config_parse_long,                  0,                             offsetof(Socket, mq_msgsize)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"Socket.TimerSlackNSec",               config_parse_nsec,                  0,                             offsetof(Socket, exec_context.timer_slack_nsec)},
      {"Unit.RequiresMountsFor",          config_parse_unit_requires_mounts_for, 0,                          offsetof(Unit, requires_mounts_for)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Socket.User",                         config_parse_unit_string_printf,    0,                             offsetof(Socket, exec_context.user)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"Socket.StandardInput",                config_parse_input,                 0,                             offsetof(Socket, exec_context.std_input)},
      {"Socket.StandardOutput",               config_parse_output,                0,                             offsetof(Socket, exec_context.std_output)},
      {"Socket.SecureBits",                   config_parse_exec_secure_bits,      0,                             offsetof(Socket, exec_context)},
      {"Unit.Requires",                   config_parse_unit_deps,             UNIT_REQUIRES,                 0},
      {(char*)0},
      {"Socket.PipeSize",                 config_parse_bytes_size,            0,                             offsetof(Socket, pipe_size)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Socket.LimitAS",                      config_parse_limit,                 RLIMIT_AS,                     offsetof(Socket, exec_context.rlimit)},
      {"Socket.StandardError",                config_parse_output,                0,                             offsetof(Socket, exec_context.std_error)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Unit.RequiresOverridable",        config_parse_unit_deps,             UNIT_REQUIRES_OVERRIDABLE,     0},
      {(char*)0},
      {"Mount.SecureBits",                   config_parse_exec_secure_bits,      0,                             offsetof(Mount, exec_context)},
      {"Unit.AllowIsolate",               config_parse_bool,                  0,                             offsetof(Unit, allow_isolate)},
      {"Socket.Transparent",              config_parse_bool,                  0,                             offsetof(Socket, transparent)},
      {(char*)0},
      {"Swap.NoNewPrivileges",              config_parse_bool,                  0,                             offsetof(Swap, exec_context.no_new_privileges)},
      {"Mount.EnvironmentFile",              config_parse_unit_env_file,         0,                             offsetof(Mount, exec_context.environment_files)},
      {"Mount.Environment",                  config_parse_environ,               0,                             offsetof(Mount, exec_context.environment)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Socket.MaxConnections",           config_parse_unsigned,              0,                             offsetof(Socket, max_connections)},
      {"Socket.MountFlags",                   config_parse_exec_mount_flags,      0,                             offsetof(Socket, exec_context)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Socket.Broadcast",                config_parse_bool,                  0,                             offsetof(Socket, broadcast)},
      {"Socket.TimeoutSec",               config_parse_sec,                   0,                             offsetof(Socket, timeout_usec)},
      {(char*)0}, {(char*)0},
      {"Socket.MessageQueueMaxMessages",  config_parse_long,                  0,                             offsetof(Socket, mq_maxmsg)},
      {(char*)0}, {(char*)0},
      {"Service.StartLimitBurst",         config_parse_unsigned,              0,                             offsetof(Service, start_limit.burst)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Mount.ControlGroupAttribute",        config_parse_unit_cgroup_attr,      0,                             0},
      {"Swap.StandardError",                config_parse_output,                0,                             offsetof(Swap, exec_context.std_error)},
      {"Mount.InaccessibleDirectories",      config_parse_path_strv,             0,                             offsetof(Mount, exec_context.inaccessible_dirs)},
      {"Swap.MemorySoftLimit",              config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {(char*)0},
      {"Swap.IOSchedulingClass",            config_parse_exec_io_class,         0,                             offsetof(Swap, exec_context)},
      {"Mount.ControlGroupPersistent",       config_parse_tristate,              0,                             offsetof(Mount, exec_context.control_group_persistent)},
      {"Swap.StandardOutput",               config_parse_output,                0,                             offsetof(Swap, exec_context.std_output)},
      {(char*)0},
      {"Mount.ReadWriteDirectories",         config_parse_path_strv,             0,                             offsetof(Mount, exec_context.read_write_dirs)},
      {(char*)0}, {(char*)0},
      {"Mount.KillMode",                     config_parse_kill_mode,             0,                             offsetof(Mount, kill_context.kill_mode)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Mount.Options",                   config_parse_string,                0,                             offsetof(Mount, parameters_fragment.options)},
      {(char*)0},
      {"Swap.EnvironmentFile",              config_parse_unit_env_file,         0,                             offsetof(Swap, exec_context.environment_files)},
      {"Swap.Environment",                  config_parse_environ,               0,                             offsetof(Swap, exec_context.environment)},
      {"Socket.NoNewPrivileges",              config_parse_bool,                  0,                             offsetof(Socket, exec_context.no_new_privileges)},
      {"Swap.KillMode",                     config_parse_kill_mode,             0,                             offsetof(Swap, kill_context.kill_mode)},
      {(char*)0}, {(char*)0},
      {"Swap.ControlGroupAttribute",        config_parse_unit_cgroup_attr,      0,                             0},
      {(char*)0},
      {"Unit.Documentation",              config_parse_documentation,         0,                             offsetof(Unit, documentation)},
      {"Swap.OOMScoreAdjust",               config_parse_exec_oom_score_adjust, 0,                             offsetof(Swap, exec_context)},
      {(char*)0}, {(char*)0},
      {"Swap.ControlGroupPersistent",       config_parse_tristate,              0,                             offsetof(Swap, exec_context.control_group_persistent)},
      {"Swap.StandardInput",                config_parse_input,                 0,                             offsetof(Swap, exec_context.std_input)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"Socket.CapabilityBoundingSet",        config_parse_bounding_set,          0,                             offsetof(Socket, exec_context.capability_bounding_set_drop)},
      {"Swap.CPUShares",                    config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {"Socket.LimitRSS",                     config_parse_limit,                 RLIMIT_RSS,                    offsetof(Socket, exec_context.rlimit)},
      {"Service.StandardInput",                config_parse_input,                 0,                             offsetof(Service, exec_context.std_input)},
      {"Service.StandardOutput",               config_parse_output,                0,                             offsetof(Service, exec_context.std_output)},
      {"Socket.DeviceAllow",                  config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {"Service.StartLimitAction",        config_parse_start_limit_action,    0,                             offsetof(Service, start_limit_action)},
      {(char*)0}, {(char*)0},
      {"Swap.LimitAS",                      config_parse_limit,                 RLIMIT_AS,                     offsetof(Swap, exec_context.rlimit)},
      {"Swap.LimitRSS",                     config_parse_limit,                 RLIMIT_RSS,                    offsetof(Swap, exec_context.rlimit)},
      {(char*)0},
      {"Socket.ReceiveBuffer",            config_parse_bytes_size,            0,                             offsetof(Socket, receive_buffer)},
      {"Service.StandardError",                config_parse_output,                0,                             offsetof(Service, exec_context.std_error)},
      {"Socket.DeviceDeny",                   config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"Path.MakeDirectory",              config_parse_bool,                  0,                             offsetof(Path, make_directory)},
      {"Mount.TTYReset",                     config_parse_bool,                  0,                             offsetof(Mount, exec_context.tty_reset)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"Socket.ControlGroupAttribute",        config_parse_unit_cgroup_attr,      0,                             0},
      {"Mount.BlockIOWeight",                config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {"Socket.InaccessibleDirectories",      config_parse_path_strv,             0,                             offsetof(Socket, exec_context.inaccessible_dirs)},
      {"Socket.SupplementaryGroups",          config_parse_strv,                  0,                             offsetof(Socket, exec_context.supplementary_groups)},
      {(char*)0},
      {"Swap.Priority",                   config_parse_int,                   0,                             offsetof(Swap, parameters_fragment.priority)},
      {"Socket.ControlGroupPersistent",       config_parse_tristate,              0,                             offsetof(Socket, exec_context.control_group_persistent)},
      {(char*)0}, {(char*)0},
      {"Swap.Capabilities",                 config_parse_exec_capabilities,     0,                             offsetof(Swap, exec_context)},
      {(char*)0},
      {"Socket.Capabilities",                 config_parse_exec_capabilities,     0,                             offsetof(Socket, exec_context)},
      {"Socket.TCPCongestion",            config_parse_string,                0,                             offsetof(Socket, tcp_congestion)},
      {"Unit.OnFailureIsolate",           config_parse_bool,                  0,                             offsetof(Unit, on_failure_isolate)},
      {(char*)0},
      {"Swap.RootDirectory",                config_parse_unit_path_printf,      0,                             offsetof(Swap, exec_context.root_directory)},
      {"Mount.DirectoryMode",             config_parse_mode,                  0,                             offsetof(Mount, directory_mode)},
      {(char*)0},
      {"Service.StartLimitInterval",      config_parse_sec,                   0,                             offsetof(Service, start_limit.interval)},
      {(char*)0},
      {"Socket.SystemCallFilter",             config_parse_syscall_filter,        0,                             offsetof(Socket, exec_context)},
      {"Swap.ReadOnlyDirectories",          config_parse_path_strv,             0,                             offsetof(Swap, exec_context.read_only_dirs)},
      {"Service.SuccessExitStatus",       config_parse_set_status,            0,                             offsetof(Service, success_status)},
      {(char*)0},
      {"Socket.LimitLOCKS",                   config_parse_limit,                 RLIMIT_LOCKS,                  offsetof(Socket, exec_context.rlimit)},
      {"Swap.TTYReset",                     config_parse_bool,                  0,                             offsetof(Swap, exec_context.tty_reset)},
      {"Mount.RootDirectory",                config_parse_unit_path_printf,      0,                             offsetof(Mount, exec_context.root_directory)},
      {"Service.Restart",                 config_parse_service_restart,       0,                             offsetof(Service, restart)},
      {(char*)0},
      {"Mount.SyslogIdentifier",             config_parse_unit_string_printf,    0,                             offsetof(Mount, exec_context.syslog_identifier)},
      {(char*)0}, {(char*)0},
      {"Socket.FreeBind",                 config_parse_bool,                  0,                             offsetof(Socket, free_bind)},
      {(char*)0}, {(char*)0},
      {"Service.RestartSec",              config_parse_sec,                   0,                             offsetof(Service, restart_usec)},
      {"Mount.StandardInput",                config_parse_input,                 0,                             offsetof(Mount, exec_context.std_input)},
      {"Automount.Where",                 config_parse_path,                  0,                             offsetof(Automount, where)},
      {"Socket.UtmpIdentifier",               config_parse_unit_string_printf,    0,                             offsetof(Socket, exec_context.utmp_id)},
      {"Mount.DeviceAllow",                  config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {"Socket.SyslogIdentifier",             config_parse_unit_string_printf,    0,                             offsetof(Socket, exec_context.syslog_identifier)},
      {(char*)0},
      {"Swap.IOSchedulingPriority",         config_parse_exec_io_priority,      0,                             offsetof(Swap, exec_context)},
      {"Unit.ConditionKernelCommandLine", config_parse_unit_condition_string, CONDITION_KERNEL_COMMAND_LINE, 0},
      {"Socket.KillSignal",                   config_parse_kill_signal,           0,                             offsetof(Socket, kill_context.kill_signal)},
      {"Socket.Accept",                   config_parse_bool,                  0,                             offsetof(Socket, accept)},
      {"Service.SystemCallFilter",             config_parse_syscall_filter,        0,                             offsetof(Service, exec_context)},
      {"Mount.Type",                      config_parse_string,                0,                             offsetof(Mount, parameters_fragment.fstype)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Socket.Backlog",                  config_parse_unsigned,              0,                             offsetof(Socket, backlog)},
      {(char*)0},
      {"Mount.KillSignal",                   config_parse_kill_signal,           0,                             offsetof(Mount, kill_context.kill_signal)},
      {"Socket.PassCredentials",          config_parse_bool,                  0,                             offsetof(Socket, pass_cred)},
      {(char*)0},
      {"Service.ControlGroupAttribute",        config_parse_unit_cgroup_attr,      0,                             0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Unit.ConditionVirtualization",    config_parse_unit_condition_string, CONDITION_VIRTUALIZATION,      0},
      {(char*)0},
      {"Service.ControlGroupPersistent",       config_parse_tristate,              0,                             offsetof(Service, exec_context.control_group_persistent)},
      {"Mount.Group",                        config_parse_unit_string_printf,    0,                             offsetof(Mount, exec_context.group)},
      {(char*)0},
      {"Mount.IOSchedulingClass",            config_parse_exec_io_class,         0,                             offsetof(Mount, exec_context)},
      {(char*)0},
      {"Service.IOSchedulingClass",            config_parse_exec_io_class,         0,                             offsetof(Service, exec_context)},
      {"Swap.MemoryLimit",                  config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {(char*)0},
      {"Swap.InaccessibleDirectories",      config_parse_path_strv,             0,                             offsetof(Swap, exec_context.inaccessible_dirs)},
      {"Swap.UtmpIdentifier",               config_parse_unit_string_printf,    0,                             offsetof(Swap, exec_context.utmp_id)},
      {"Swap.Group",                        config_parse_unit_string_printf,    0,                             offsetof(Swap, exec_context.group)},
      {"Swap.SystemCallFilter",             config_parse_syscall_filter,        0,                             offsetof(Swap, exec_context)},
      {"Mount.WorkingDirectory",            config_parse_unit_path_printf,      0,                             offsetof(Mount, exec_context.working_directory)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"Mount.CapabilityBoundingSet",        config_parse_bounding_set,          0,                             offsetof(Mount, exec_context.capability_bounding_set_drop)},
      {(char*)0},
      {"Service.CapabilityBoundingSet",        config_parse_bounding_set,          0,                             offsetof(Service, exec_context.capability_bounding_set_drop)},
      {(char*)0},
      {"Swap.TTYVTDisallocate",             config_parse_bool,                  0,                             offsetof(Swap, exec_context.tty_vt_disallocate)},
      {"Unit.ConditionSecurity",          config_parse_unit_condition_string, CONDITION_SECURITY,            0},
      {"Socket.SyslogLevel",                  config_parse_level,                 0,                             offsetof(Socket, exec_context.syslog_priority)},
      {"Mount.ControlGroupModify",           config_parse_bool,                  0,                             offsetof(Mount, exec_context.control_group_modify)},
      {"Swap.MountFlags",                   config_parse_exec_mount_flags,      0,                             offsetof(Swap, exec_context)},
      {"Path.PathChanged",                config_parse_path_spec,             0,                             0},
      {"Service.CPUShares",                    config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"Service.RestartPreventExitStatus", config_parse_set_status,           0,                             offsetof(Service, restart_ignore_status)},
      {(char*)0},
      {"Socket.ExecStartPre",             config_parse_exec,                  SOCKET_EXEC_START_PRE,         offsetof(Socket, exec_command)},
      {"Timer.Unit",                      config_parse_trigger_unit,          0,                             0},
      {"Service.InaccessibleDirectories",      config_parse_path_strv,             0,                             offsetof(Service, exec_context.inaccessible_dirs)},
      {"Path.PathModified",               config_parse_path_spec,             0,                             0},
      {(char*)0}, {(char*)0},
      {"Socket.ExecStartPost",            config_parse_exec,                  SOCKET_EXEC_START_POST,        offsetof(Socket, exec_command)},
      {"Mount.DeviceDeny",                   config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {(char*)0}, {(char*)0},
      {"Socket.PassSecurity",             config_parse_bool,                  0,                             offsetof(Socket, pass_sec)},
      {(char*)0},
      {"Unit.Description",                config_parse_unit_string_printf,    0,                             offsetof(Unit, description)},
      {(char*)0},
      {"Swap.ControlGroupModify",           config_parse_bool,                  0,                             offsetof(Swap, exec_context.control_group_modify)},
      {"Unit.ConditionPathIsReadWrite",   config_parse_unit_condition_path,   CONDITION_PATH_IS_READ_WRITE,  0},
      {"Swap.SecureBits",                   config_parse_exec_secure_bits,      0,                             offsetof(Swap, exec_context)},
      {(char*)0}, {(char*)0},
      {"Service.ReadWriteDirectories",         config_parse_path_strv,             0,                             offsetof(Service, exec_context.read_write_dirs)},
      {"Socket.ListenStream",             config_parse_socket_listen,         SOCKET_SOCKET,                 0},
      {"Unit.ConditionPathIsMountPoint",  config_parse_unit_condition_path,   CONDITION_PATH_IS_MOUNT_POINT, 0},
      {"Unit.StopWhenUnneeded",           config_parse_bool,                  0,                             offsetof(Unit, stop_when_unneeded)},
      {"Socket.LimitSIGPENDING",              config_parse_limit,                 RLIMIT_SIGPENDING,             offsetof(Socket, exec_context.rlimit)},
      {"Mount.Capabilities",                 config_parse_exec_capabilities,     0,                             offsetof(Mount, exec_context)},
      {"Unit.DefaultDependencies",        config_parse_bool,                  0,                             offsetof(Unit, default_dependencies)},
      {"Service.Capabilities",                 config_parse_exec_capabilities,     0,                             offsetof(Service, exec_context)},
      {"Swap.CapabilityBoundingSet",        config_parse_bounding_set,          0,                             offsetof(Swap, exec_context.capability_bounding_set_drop)},
      {"Service.Type",                    config_parse_service_type,          0,                             offsetof(Service, type)},
      {"Service.SecureBits",                   config_parse_exec_secure_bits,      0,                             offsetof(Service, exec_context)},
      {"Socket.BindIPv6Only",             config_parse_socket_bind,           0,                             0,},
      {(char*)0},
      {"Service.KillMode",                     config_parse_kill_mode,             0,                             offsetof(Service, kill_context.kill_mode)},
      {(char*)0},
      {"Unit.PropagatesReloadTo",         config_parse_unit_deps,             UNIT_PROPAGATES_RELOAD_TO,     0},
      {"Socket.BindToDevice",             config_parse_socket_bindtodevice,   0,                             0},
      {"Socket.TTYReset",                     config_parse_bool,                  0,                             offsetof(Socket, exec_context.tty_reset)},
      {"Unit.PartOf",                     config_parse_unit_deps,             UNIT_PART_OF,                  0},
      {(char*)0},
      {"Unit.JobTimeoutSec",              config_parse_sec,                   0,                             offsetof(Unit, job_timeout)},
      {"Unit.ConditionCapability",        config_parse_unit_condition_string, CONDITION_CAPABILITY,          0},
      {"Socket.ListenSpecial",            config_parse_socket_listen,         SOCKET_SPECIAL,                0},
      {"Socket.ListenDatagram",           config_parse_socket_listen,         SOCKET_SOCKET,                 0},
      {"Mount.TCPWrapName",                  config_parse_unit_string_printf,    0,                             offsetof(Mount, exec_context.tcpwrap_name)},
      {"Mount.ControlGroup",                 config_parse_unit_cgroup,           0,                             0},
      {"Service.WatchdogSec",             config_parse_sec,                   0,                             offsetof(Service, watchdog_usec)},
      {(char*)0},
      {"Swap.SyslogIdentifier",             config_parse_unit_string_printf,    0,                             offsetof(Swap, exec_context.syslog_identifier)},
      {"Socket.LimitNPROC",                   config_parse_limit,                 RLIMIT_NPROC,                  offsetof(Socket, exec_context.rlimit)},
      {"Service.TimeoutSec",              config_parse_service_timeout,       0,                             offsetof(Service, timeout_start_usec)},
      {(char*)0},
      {"Path.PathExists",                 config_parse_path_spec,             0,                             0},
      {(char*)0},
      {"Service.TimeoutStopSec",          config_parse_service_timeout,       0,                             offsetof(Service, timeout_stop_usec)},
      {"Service.TimeoutStartSec",         config_parse_service_timeout,       0,                             offsetof(Service, timeout_start_usec)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"Service.SyslogIdentifier",             config_parse_unit_string_printf,    0,                             offsetof(Service, exec_context.syslog_identifier)},
      {"Socket.ControlGroupModify",           config_parse_bool,                  0,                             offsetof(Socket, exec_context.control_group_modify)},
      {(char*)0},
      {"Mount.SyslogLevel",                  config_parse_level,                 0,                             offsetof(Mount, exec_context.syslog_priority)},
      {"Mount.TTYPath",                      config_parse_unit_path_printf,      0,                             offsetof(Mount, exec_context.tty_path)},
      {"Unit.ConditionPathExists",        config_parse_unit_condition_path,   CONDITION_PATH_EXISTS,         0},
      {"Socket.Priority",                 config_parse_int,                   0,                             offsetof(Socket, priority)},
      {"Mount.TimeoutSec",                config_parse_sec,                   0,                             offsetof(Mount, timeout_usec)},
      {"Swap.ControlGroup",                 config_parse_unit_cgroup,           0,                             0},
      {(char*)0},
      {"Swap.CPUSchedulingPolicy",          config_parse_exec_cpu_sched_policy, 0,                             offsetof(Swap, exec_context)},
      {(char*)0},
      {"Swap.CPUSchedulingPriority",        config_parse_exec_cpu_sched_prio,   0,                             offsetof(Swap, exec_context)},
      {"Socket.ReadWriteDirectories",         config_parse_path_strv,             0,                             offsetof(Socket, exec_context.read_write_dirs)},
      {(char*)0}, {(char*)0},
      {"Mount.SupplementaryGroups",          config_parse_strv,                  0,                             offsetof(Mount, exec_context.supplementary_groups)},
      {"Mount.IOSchedulingPriority",         config_parse_exec_io_priority,      0,                             offsetof(Mount, exec_context)},
      {(char*)0},
      {"Service.IOSchedulingPriority",         config_parse_exec_io_priority,      0,                             offsetof(Service, exec_context)},
      {(char*)0},
      {"Mount.UtmpIdentifier",               config_parse_unit_string_printf,    0,                             offsetof(Mount, exec_context.utmp_id)},
      {"Socket.SyslogFacility",               config_parse_facility,              0,                             offsetof(Socket, exec_context.syslog_priority)},
      {"Socket.EnvironmentFile",              config_parse_unit_env_file,         0,                             offsetof(Socket, exec_context.environment_files)},
      {"Socket.Environment",                  config_parse_environ,               0,                             offsetof(Socket, exec_context.environment)},
      {(char*)0},
      {"Mount.SyslogFacility",               config_parse_facility,              0,                             offsetof(Mount, exec_context.syslog_priority)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Socket.SyslogLevelPrefix",            config_parse_bool,                  0,                             offsetof(Socket, exec_context.syslog_level_prefix)},
      {"Service.LimitAS",                      config_parse_limit,                 RLIMIT_AS,                     offsetof(Service, exec_context.rlimit)},
      {"Service.LimitRSS",                     config_parse_limit,                 RLIMIT_RSS,                    offsetof(Service, exec_context.rlimit)},
      {"Service.CPUSchedulingPolicy",          config_parse_exec_cpu_sched_policy, 0,                             offsetof(Service, exec_context)},
      {(char*)0},
      {"Service.CPUSchedulingPriority",        config_parse_exec_cpu_sched_prio,   0,                             offsetof(Service, exec_context)},
      {"Service.ExecStopPost",            config_parse_exec,                  SERVICE_EXEC_STOP_POST,        offsetof(Service, exec_command)},
      {(char*)0},
      {"Service.User",                         config_parse_unit_string_printf,    0,                             offsetof(Service, exec_context.user)},
      {(char*)0},
      {"Unit.Conflicts",                  config_parse_unit_deps,             UNIT_CONFLICTS,                0},
      {"Service.ExecStartPre",            config_parse_exec,                  SERVICE_EXEC_START_PRE,        offsetof(Service, exec_command)},
      {"Service.RootDirectory",                config_parse_unit_path_printf,      0,                             offsetof(Service, exec_context.root_directory)},
      {"Service.ExecStart",               config_parse_exec,                  SERVICE_EXEC_START,            offsetof(Service, exec_command)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Service.ExecStartPost",           config_parse_exec,                  SERVICE_EXEC_START_POST,       offsetof(Service, exec_command)},
      {"Service.ReadOnlyDirectories",          config_parse_path_strv,             0,                             offsetof(Service, exec_context.read_only_dirs)},
      {(char*)0},
      {"Path.PathExistsGlob",             config_parse_path_spec,             0,                             0},
      {"Service.RootDirectoryStartOnly",  config_parse_bool,                  0,                             offsetof(Service, root_directory_start_only)},
      {"Mount.TTYVHangup",                   config_parse_bool,                  0,                             offsetof(Mount, exec_context.tty_vhangup)},
      {(char*)0},
      {"Service.Group",                        config_parse_unit_string_printf,    0,                             offsetof(Service, exec_context.group)},
      {"Socket.ControlGroup",                 config_parse_unit_cgroup,           0,                             0},
      {(char*)0},
      {"Service.ControlGroupModify",           config_parse_bool,                  0,                             offsetof(Service, exec_context.control_group_modify)},
      {"Socket.IPTOS",                    config_parse_ip_tos,                0,                             offsetof(Socket, ip_tos)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"Unit.ConditionPathExistsGlob",    config_parse_unit_condition_path,   CONDITION_PATH_EXISTS_GLOB,    0},
      {(char*)0},
      {"Mount.TimerSlackNSec",               config_parse_nsec,                  0,                             offsetof(Mount, exec_context.timer_slack_nsec)},
      {(char*)0}, {(char*)0},
      {"Service.EnvironmentFile",              config_parse_unit_env_file,         0,                             offsetof(Service, exec_context.environment_files)},
      {"Service.Environment",                  config_parse_environ,               0,                             offsetof(Service, exec_context.environment)},
      {(char*)0},
      {"Mount.BlockIOReadBandwidth",         config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Swap.KillSignal",                   config_parse_kill_signal,           0,                             offsetof(Swap, kill_context.kill_signal)},
      {"Swap.SyslogLevel",                  config_parse_level,                 0,                             offsetof(Swap, exec_context.syslog_priority)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Service.SysVStartPriority",      config_parse_sysv_priority,         0,                             offsetof(Service, sysv_start_priority)},
      {"Socket.OOMScoreAdjust",               config_parse_exec_oom_score_adjust, 0,                             offsetof(Socket, exec_context)},
      {"Service.TimerSlackNSec",               config_parse_nsec,                  0,                             offsetof(Service, exec_context.timer_slack_nsec)},
      {(char*)0},
      {"Mount.StandardError",                config_parse_output,                0,                             offsetof(Mount, exec_context.std_error)},
      {"Socket.KillMode",                     config_parse_kill_mode,             0,                             offsetof(Socket, kill_context.kill_mode)},
      {(char*)0},
      {"Mount.BlockIOWriteBandwidth",        config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {"Install.RequiredBy",              NULL,                               0,                             0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Service.Nice",                         config_parse_exec_nice,             0,                             offsetof(Service, exec_context)},
      {"Path.DirectoryMode",              config_parse_mode,                  0,                             offsetof(Path, directory_mode)},
      {(char*)0},
      {"Socket.ListenNetlink",            config_parse_socket_listen,         SOCKET_SOCKET,                 0},
      {(char*)0}, {(char*)0},
      {"Swap.BlockIOWeight",                config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {(char*)0},
      {"Unit.RequisiteOverridable",       config_parse_unit_deps,             UNIT_REQUISITE_OVERRIDABLE,    0},
      {"Timer.OnCalendar",                config_parse_timer,                 0,                             0},
      {"Swap.PAMName",                      config_parse_unit_string_printf,    0,                             offsetof(Swap, exec_context.pam_name)},
      {"Mount.SyslogLevelPrefix",            config_parse_bool,                  0,                             offsetof(Mount, exec_context.syslog_level_prefix)},
      {(char*)0},
      {"Timer.OnBootSec",                 config_parse_timer,                 0,                             0},
      {"Socket.Mark",                     config_parse_int,                   0,                             offsetof(Socket, mark)},
      {"Socket.Group",                        config_parse_unit_string_printf,    0,                             offsetof(Socket, exec_context.group)},
      {(char*)0}, {(char*)0},
      {"Service.ControlGroup",                 config_parse_unit_cgroup,           0,                             0},
      {(char*)0},
      {"Unit.PropagateReloadTo",          config_parse_unit_deps,             UNIT_PROPAGATES_RELOAD_TO,     0},
      {(char*)0},
      {"Unit.ConditionPathIsDirectory",   config_parse_unit_condition_path,   CONDITION_PATH_IS_DIRECTORY,   0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"Mount.PrivateNetwork",               config_parse_bool,                  0,                             offsetof(Mount, exec_context.private_network)},
      {"Socket.CPUSchedulingPolicy",          config_parse_exec_cpu_sched_policy, 0,                             offsetof(Socket, exec_context)},
      {(char*)0},
      {"Socket.CPUSchedulingPriority",        config_parse_exec_cpu_sched_prio,   0,                             offsetof(Socket, exec_context)},
      {(char*)0}, {(char*)0},
      {"Mount.UMask",                        config_parse_mode,                  0,                             offsetof(Mount, exec_context.umask)},
      {(char*)0}, {(char*)0},
      {"Service.SendSIGKILL",                 config_parse_bool,                  0,                             offsetof(Service, kill_context.send_sigkill)},
      {"Unit.IgnoreOnIsolate",            config_parse_bool,                  0,                             offsetof(Unit, ignore_on_isolate)},
      {"Socket.LimitNICE",                    config_parse_limit,                 RLIMIT_NICE,                   offsetof(Socket, exec_context.rlimit)},
      {(char*)0},
      {"Socket.SendSIGKILL",                 config_parse_bool,                  0,                             offsetof(Socket, kill_context.send_sigkill)},
      {"Service.TTYVTDisallocate",             config_parse_bool,                  0,                             offsetof(Service, exec_context.tty_vt_disallocate)},
      {"Swap.ReadWriteDirectories",         config_parse_path_strv,             0,                             offsetof(Swap, exec_context.read_write_dirs)},
      {"Unit.IgnoreOnSnapshot",           config_parse_bool,                  0,                             offsetof(Unit, ignore_on_snapshot)},
      {"Mount.SystemCallFilter",             config_parse_syscall_filter,        0,                             offsetof(Mount, exec_context)},
      {"Service.ExecReload",              config_parse_exec,                  SERVICE_EXEC_RELOAD,           offsetof(Service, exec_command)},
      {(char*)0},
      {"Mount.StandardOutput",               config_parse_output,                0,                             offsetof(Mount, exec_context.std_output)},
      {(char*)0},
      {"Socket.SendBuffer",               config_parse_bytes_size,            0,                             offsetof(Socket, send_buffer)},
      {"Socket.ExecStopPre",              config_parse_exec,                  SOCKET_EXEC_STOP_PRE,          offsetof(Socket, exec_command)},
      {"Service.SyslogLevel",                  config_parse_level,                 0,                             offsetof(Service, exec_context.syslog_priority)},
      {(char*)0}, {(char*)0},
      {"Unit.RefuseManualStart",          config_parse_bool,                  0,                             offsetof(Unit, refuse_manual_start)},
      {(char*)0},
      {"Socket.ExecStopPost",             config_parse_exec,                  SOCKET_EXEC_STOP_POST,         offsetof(Socket, exec_command)},
      {"Swap.UMask",                        config_parse_mode,                  0,                             offsetof(Swap, exec_context.umask)},
      {(char*)0},
      {"Socket.LimitFSIZE",                   config_parse_limit,                 RLIMIT_FSIZE,                  offsetof(Socket, exec_context.rlimit)},
      {(char*)0},
      {"Socket.PAMName",                      config_parse_unit_string_printf,    0,                             offsetof(Socket, exec_context.pam_name)},
      {"Socket.LimitMSGQUEUE",                config_parse_limit,                 RLIMIT_MSGQUEUE,               offsetof(Socket, exec_context.rlimit)},
      {(char*)0}, {(char*)0},
      {"Service.KillSignal",                   config_parse_kill_signal,           0,                             offsetof(Service, kill_context.kill_signal)},
      {"Swap.LimitNICE",                    config_parse_limit,                 RLIMIT_NICE,                   offsetof(Swap, exec_context.rlimit)},
      {"Mount.CPUShares",                    config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {"Mount.FsckPassNo",                config_parse_fsck_passno,           0,                             offsetof(Mount, parameters_fragment.passno)},
      {(char*)0}, {(char*)0},
      {"Swap.PrivateNetwork",               config_parse_bool,                  0,                             offsetof(Swap, exec_context.private_network)},
      {"Swap.PrivateTmp",                   config_parse_bool,                  0,                             offsetof(Swap, exec_context.private_tmp)},
      {(char*)0},
      {"Service.OOMScoreAdjust",               config_parse_exec_oom_score_adjust, 0,                             offsetof(Service, exec_context)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Service.TTYReset",                     config_parse_bool,                  0,                             offsetof(Service, exec_context.tty_reset)},
      {"Mount.TTYVTDisallocate",             config_parse_bool,                  0,                             offsetof(Mount, exec_context.tty_vt_disallocate)},
      {"Service.NoNewPrivileges",              config_parse_bool,                  0,                             offsetof(Service, exec_context.no_new_privileges)},
      {(char*)0},
      {"Unit.ConditionFileIsExecutable",  config_parse_unit_condition_path,   CONDITION_FILE_IS_EXECUTABLE,  0},
      {(char*)0},
      {"Swap.SyslogLevelPrefix",            config_parse_bool,                  0,                             offsetof(Swap, exec_context.syslog_level_prefix)},
      {"Service.LimitSIGPENDING",              config_parse_limit,                 RLIMIT_SIGPENDING,             offsetof(Service, exec_context.rlimit)},
      {(char*)0},
      {"Swap.LimitNPROC",                   config_parse_limit,                 RLIMIT_NPROC,                  offsetof(Swap, exec_context.rlimit)},
      {"Unit.ConditionACPower",           config_parse_unit_condition_string, CONDITION_AC_POWER,            0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Mount.ReadOnlyDirectories",          config_parse_path_strv,             0,                             offsetof(Mount, exec_context.read_only_dirs)},
      {"Socket.KeepAlive",                config_parse_bool,                  0,                             offsetof(Socket, keep_alive)},
      {(char*)0},
      {"Service.MemorySoftLimit",              config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {(char*)0}, {(char*)0},
      {"Socket.CPUShares",                    config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {(char*)0},
      {"Service.PrivateTmp",                   config_parse_bool,                  0,                             offsetof(Service, exec_context.private_tmp)},
      {(char*)0}, {(char*)0},
      {"Mount.PrivateTmp",                   config_parse_bool,                  0,                             offsetof(Mount, exec_context.private_tmp)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Socket.RootDirectory",                config_parse_unit_path_printf,      0,                             offsetof(Socket, exec_context.root_directory)},
      {"Socket.LimitCORE",                    config_parse_limit,                 RLIMIT_CORE,                   offsetof(Socket, exec_context.rlimit)},
      {"Install.Also",                    NULL,                               0,                             0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"Socket.WorkingDirectory",            config_parse_unit_path_printf,      0,                             offsetof(Socket, exec_context.working_directory)},
      {"Swap.TimerSlackNSec",               config_parse_nsec,                  0,                             offsetof(Swap, exec_context.timer_slack_nsec)},
      {(char*)0}, {(char*)0},
      {"Socket.ListenFIFO",               config_parse_socket_listen,         SOCKET_FIFO,                   0},
      {(char*)0},
      {"Socket.TTYPath",                      config_parse_unit_path_printf,      0,                             offsetof(Socket, exec_context.tty_path)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Unit.ConditionNull",              config_parse_unit_condition_null,   0,                             0},
      {"Mount.IgnoreSIGPIPE",                config_parse_bool,                  0,                             offsetof(Mount, exec_context.ignore_sigpipe)},
      {(char*)0},
      {"Swap.DeviceAllow",                  config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"Unit.ConditionDirectoryNotEmpty", config_parse_unit_condition_path,   CONDITION_DIRECTORY_NOT_EMPTY, 0},
      {"Socket.PrivateTmp",                   config_parse_bool,                  0,                             offsetof(Socket, exec_context.private_tmp)},
      {(char*)0}, {(char*)0},
      {"Swap.LimitLOCKS",                   config_parse_limit,                 RLIMIT_LOCKS,                  offsetof(Swap, exec_context.rlimit)},
      {"Service.BlockIOWeight",                config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {(char*)0},
      {"Socket.TCPWrapName",                  config_parse_unit_string_printf,    0,                             offsetof(Socket, exec_context.tcpwrap_name)},
      {"Mount.LimitRSS",                     config_parse_limit,                 RLIMIT_RSS,                    offsetof(Mount, exec_context.rlimit)},
      {(char*)0}, {(char*)0},
      {"Mount.SendSIGKILL",                 config_parse_bool,                  0,                             offsetof(Mount, kill_context.send_sigkill)},
      {(char*)0}, {(char*)0},
      {"Service.BusName",                 config_parse_unit_string_printf,    0,                             offsetof(Service, bus_name)},
      {"Service.IgnoreSIGPIPE",                config_parse_bool,                  0,                             offsetof(Service, exec_context.ignore_sigpipe)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Service.SyslogLevelPrefix",            config_parse_bool,                  0,                             offsetof(Service, exec_context.syslog_level_prefix)},
      {"Service.ExecStop",                config_parse_exec,                  SERVICE_EXEC_STOP,             offsetof(Service, exec_command)},
      {(char*)0}, {(char*)0},
      {"Swap.SupplementaryGroups",          config_parse_strv,                  0,                             offsetof(Swap, exec_context.supplementary_groups)},
      {(char*)0}, {(char*)0},
      {"Service.UtmpIdentifier",               config_parse_unit_string_printf,    0,                             offsetof(Service, exec_context.utmp_id)},
      {"Install.Alias",                   NULL,                               0,                             0},
      {(char*)0},
      {"Service.GuessMainPID",            config_parse_bool,                  0,                             offsetof(Service, guess_main_pid)},
      {(char*)0}, {(char*)0},
      {"Timer.OnStartupSec",              config_parse_timer,                 0,                             0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"Service.LimitNPROC",                   config_parse_limit,                 RLIMIT_NPROC,                  offsetof(Service, exec_context.rlimit)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Path.DirectoryNotEmpty",          config_parse_path_spec,             0,                             0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Service.Sockets",                 config_parse_service_sockets,       0,                             0},
      {"Swap.SendSIGKILL",                 config_parse_bool,                  0,                             offsetof(Swap, kill_context.send_sigkill)},
      {(char*)0},
      {"Swap.LimitCPU",                     config_parse_limit,                 RLIMIT_CPU,                    offsetof(Swap, exec_context.rlimit)},
      {"Socket.LimitMEMLOCK",                 config_parse_limit,                 RLIMIT_MEMLOCK,                offsetof(Socket, exec_context.rlimit)},
      {"Socket.IgnoreSIGPIPE",                config_parse_bool,                  0,                             offsetof(Socket, exec_context.ignore_sigpipe)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Swap.CPUSchedulingResetOnFork",     config_parse_bool,                  0,                             offsetof(Swap, exec_context.cpu_sched_reset_on_fork)},
      {(char*)0},
      {"Socket.ReadOnlyDirectories",          config_parse_path_strv,             0,                             offsetof(Socket, exec_context.read_only_dirs)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"Service.MountFlags",                   config_parse_exec_mount_flags,      0,                             offsetof(Service, exec_context)},
      {(char*)0}, {(char*)0},
      {"Install.WantedBy",                NULL,                               0,                             0},
      {(char*)0},
      {"Service.LimitFSIZE",                   config_parse_limit,                 RLIMIT_FSIZE,                  offsetof(Service, exec_context.rlimit)},
      {(char*)0}, {(char*)0},
      {"Service.LimitMSGQUEUE",                config_parse_limit,                 RLIMIT_MSGQUEUE,               offsetof(Service, exec_context.rlimit)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"Service.CPUSchedulingResetOnFork",     config_parse_bool,                  0,                             offsetof(Service, exec_context.cpu_sched_reset_on_fork)},
      {(char*)0}, {(char*)0},
      {"Swap.LimitSIGPENDING",              config_parse_limit,                 RLIMIT_SIGPENDING,             offsetof(Swap, exec_context.rlimit)},
      {"Timer.OnUnitActiveSec",           config_parse_timer,                 0,                             0},
      {"Service.SupplementaryGroups",          config_parse_strv,                  0,                             offsetof(Service, exec_context.supplementary_groups)},
      {(char*)0}, {(char*)0},
      {"Swap.TTYVHangup",                   config_parse_bool,                  0,                             offsetof(Swap, exec_context.tty_vhangup)},
      {"Swap.CPUAffinity",                  config_parse_exec_cpu_affinity,     0,                             offsetof(Swap, exec_context)},
      {"Socket.TTYVHangup",                   config_parse_bool,                  0,                             offsetof(Socket, exec_context.tty_vhangup)},
      {"Socket.LimitRTTIME",                  config_parse_limit,                 RLIMIT_RTTIME,                 offsetof(Socket, exec_context.rlimit)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"Service.MemoryLimit",                  config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {(char*)0},
      {"Swap.BlockIOWriteBandwidth",        config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {"Socket.LimitSTACK",                   config_parse_limit,                 RLIMIT_STACK,                  offsetof(Socket, exec_context.rlimit)},
      {"Socket.LimitRTPRIO",                  config_parse_limit,                 RLIMIT_RTPRIO,                 offsetof(Socket, exec_context.rlimit)},
      {(char*)0}, {(char*)0},
      {"Unit.ConditionFileNotEmpty",      config_parse_unit_condition_path,   CONDITION_FILE_NOT_EMPTY,      0},
      {(char*)0},
      {"Timer.OnUnitInactiveSec",         config_parse_timer,                 0,                             0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Socket.IPTTL",                    config_parse_int,                   0,                             offsetof(Socket, ip_ttl)},
      {"Socket.TTYVTDisallocate",             config_parse_bool,                  0,                             offsetof(Socket, exec_context.tty_vt_disallocate)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"Swap.BlockIOReadBandwidth",         config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"Service.PAMName",                      config_parse_unit_string_printf,    0,                             offsetof(Service, exec_context.pam_name)},
      {"Mount.LimitSTACK",                   config_parse_limit,                 RLIMIT_STACK,                  offsetof(Mount, exec_context.rlimit)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Swap.LimitSTACK",                   config_parse_limit,                 RLIMIT_STACK,                  offsetof(Swap, exec_context.rlimit)},
      {"Mount.MountFlags",                   config_parse_exec_mount_flags,      0,                             offsetof(Mount, exec_context)},
      {(char*)0},
      {"Swap.IgnoreSIGPIPE",                config_parse_bool,                  0,                             offsetof(Swap, exec_context.ignore_sigpipe)},
      {(char*)0},
      {"Swap.DeviceDeny",                   config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {"Unit.RefuseManualStop",           config_parse_bool,                  0,                             offsetof(Unit, refuse_manual_stop)},
      {(char*)0},
      {"Service.LimitLOCKS",                   config_parse_limit,                 RLIMIT_LOCKS,                  offsetof(Service, exec_context.rlimit)},
      {(char*)0},
      {"Socket.LimitCPU",                     config_parse_limit,                 RLIMIT_CPU,                    offsetof(Socket, exec_context.rlimit)},
      {(char*)0},
      {"Service.LimitNICE",                    config_parse_limit,                 RLIMIT_NICE,                   offsetof(Service, exec_context.rlimit)},
      {"Service.RemainAfterExit",         config_parse_bool,                  0,                             offsetof(Service, remain_after_exit)},
      {(char*)0},
      {"Unit.SourcePath",                 config_parse_path,                  0,                             offsetof(Unit, source_path)},
      {(char*)0},
      {"Swap.TTYPath",                      config_parse_unit_path_printf,      0,                             offsetof(Swap, exec_context.tty_path)},
      {(char*)0},
      {"Service.NonBlocking",             config_parse_bool,                  0,                             offsetof(Service, exec_context.non_blocking)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Service.LimitSTACK",                   config_parse_limit,                 RLIMIT_STACK,                  offsetof(Service, exec_context.rlimit)},
      {"Socket.IOSchedulingClass",            config_parse_exec_io_class,         0,                             offsetof(Socket, exec_context)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Unit.ConditionPathIsSymbolicLink",config_parse_unit_condition_path,   CONDITION_PATH_IS_SYMBOLIC_LINK,0},
      {"Mount.PAMName",                      config_parse_unit_string_printf,    0,                             offsetof(Mount, exec_context.pam_name)},
      {"Unit.PropagateReloadFrom",        config_parse_unit_deps,             UNIT_RELOAD_PROPAGATED_FROM,   0},
      {"Service.PIDFile",                 config_parse_unit_path_printf,      0,                             offsetof(Service, pid_file)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"Socket.CPUSchedulingResetOnFork",     config_parse_bool,                  0,                             offsetof(Socket, exec_context.cpu_sched_reset_on_fork)},
      {(char*)0},
      {"Service.TTYVHangup",                   config_parse_bool,                  0,                             offsetof(Service, exec_context.tty_vhangup)},
      {(char*)0}, {(char*)0},
      {"Swap.WorkingDirectory",            config_parse_unit_path_printf,      0,                             offsetof(Swap, exec_context.working_directory)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"Service.PrivateNetwork",               config_parse_bool,                  0,                             offsetof(Service, exec_context.private_network)},
      {(char*)0},
      {"Swap.SyslogFacility",               config_parse_facility,              0,                             offsetof(Swap, exec_context.syslog_priority)},
      {"Service.LimitMEMLOCK",                 config_parse_limit,                 RLIMIT_MEMLOCK,                offsetof(Service, exec_context.rlimit)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"Swap.LimitCORE",                    config_parse_limit,                 RLIMIT_CORE,                   offsetof(Swap, exec_context.rlimit)},
      {(char*)0}, {(char*)0},
      {"Mount.MemoryLimit",                  config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"Service.CPUAffinity",                  config_parse_exec_cpu_affinity,     0,                             offsetof(Service, exec_context)},
      {"Swap.LimitFSIZE",                   config_parse_limit,                 RLIMIT_FSIZE,                  offsetof(Swap, exec_context.rlimit)},
      {(char*)0}, {(char*)0},
      {"Service.PermissionsStartOnly",    config_parse_bool,                  0,                             offsetof(Service, permissions_start_only)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"Mount.LimitCPU",                     config_parse_limit,                 RLIMIT_CPU,                    offsetof(Mount, exec_context.rlimit)},
      {"Unit.ReloadPropagatedFrom",       config_parse_unit_deps,             UNIT_RELOAD_PROPAGATED_FROM,   0},
      {"Mount.LimitLOCKS",                   config_parse_limit,                 RLIMIT_LOCKS,                  offsetof(Mount, exec_context.rlimit)},
      {(char*)0},
      {"Swap.LimitMSGQUEUE",                config_parse_limit,                 RLIMIT_MSGQUEUE,               offsetof(Swap, exec_context.rlimit)},
      {(char*)0}, {(char*)0},
      {"Mount.LimitSIGPENDING",              config_parse_limit,                 RLIMIT_SIGPENDING,             offsetof(Mount, exec_context.rlimit)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Mount.CPUSchedulingPolicy",          config_parse_exec_cpu_sched_policy, 0,                             offsetof(Mount, exec_context)},
      {"Socket.LimitDATA",                    config_parse_limit,                 RLIMIT_DATA,                   offsetof(Socket, exec_context.rlimit)},
      {"Mount.CPUSchedulingPriority",        config_parse_exec_cpu_sched_prio,   0,                             offsetof(Mount, exec_context)},
      {"Socket.CPUAffinity",                  config_parse_exec_cpu_affinity,     0,                             offsetof(Socket, exec_context)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"Service.BlockIOReadBandwidth",         config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {"Service.BlockIOWriteBandwidth",        config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {(char*)0},
      {"Mount.MemorySoftLimit",              config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"Swap.TCPWrapName",                  config_parse_unit_string_printf,    0,                             offsetof(Swap, exec_context.tcpwrap_name)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"Service.SyslogFacility",               config_parse_facility,              0,                             offsetof(Service, exec_context.syslog_priority)},
      {(char*)0}, {(char*)0},
      {"Socket.BlockIOWeight",                config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Service.TCPWrapName",                  config_parse_unit_string_printf,    0,                             offsetof(Service, exec_context.tcpwrap_name)},
      {(char*)0},
      {"Mount.NoNewPrivileges",              config_parse_bool,                  0,                             offsetof(Mount, exec_context.no_new_privileges)},
      {(char*)0},
      {"Socket.LimitNOFILE",                  config_parse_limit,                 RLIMIT_NOFILE,                 offsetof(Socket, exec_context.rlimit)},
      {(char*)0}, {(char*)0},
      {"Service.LimitCPU",                     config_parse_limit,                 RLIMIT_CPU,                    offsetof(Service, exec_context.rlimit)},
      {"Socket.IOSchedulingPriority",         config_parse_exec_io_priority,      0,                             offsetof(Socket, exec_context)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"Service.UMask",                        config_parse_mode,                  0,                             offsetof(Service, exec_context.umask)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Socket.SmackLabelIPOut",          config_parse_string,                0,                             offsetof(Socket, smack_ip_out)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"Timer.OnActiveSec",               config_parse_timer,                 0,                             0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"Mount.LimitAS",                      config_parse_limit,                 RLIMIT_AS,                     offsetof(Mount, exec_context.rlimit)},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Mount.CPUAffinity",                  config_parse_exec_cpu_affinity,     0,                             offsetof(Mount, exec_context)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"Service.LimitRTTIME",                  config_parse_limit,                 RLIMIT_RTTIME,                 offsetof(Service, exec_context.rlimit)},
      {(char*)0},
      {"Swap.LimitRTPRIO",                  config_parse_limit,                 RLIMIT_RTPRIO,                 offsetof(Swap, exec_context.rlimit)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"Socket.SmackLabelIPIn",           config_parse_string,                0,                             offsetof(Socket, smack_ip_in)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Service.DeviceDeny",                   config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"Service.DeviceAllow",                  config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {(char*)0},
      {"Socket.PrivateNetwork",               config_parse_bool,                  0,                             offsetof(Socket, exec_context.private_network)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Socket.SmackLabel",               config_parse_string,                0,                             offsetof(Socket, smack)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"Service.LimitRTPRIO",                  config_parse_limit,                 RLIMIT_RTPRIO,                 offsetof(Service, exec_context.rlimit)},
      {"Mount.OOMScoreAdjust",               config_parse_exec_oom_score_adjust, 0,                             offsetof(Mount, exec_context)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"Swap.LimitMEMLOCK",                 config_parse_limit,                 RLIMIT_MEMLOCK,                offsetof(Swap, exec_context.rlimit)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"Socket.BlockIOReadBandwidth",         config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Swap.LimitDATA",                    config_parse_limit,                 RLIMIT_DATA,                   offsetof(Swap, exec_context.rlimit)},
      {(char*)0}, {(char*)0},
      {"Service.LimitCORE",                    config_parse_limit,                 RLIMIT_CORE,                   offsetof(Service, exec_context.rlimit)},
      {(char*)0},
      {"Service.LimitNOFILE",                  config_parse_limit,                 RLIMIT_NOFILE,                 offsetof(Service, exec_context.rlimit)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"Service.NotifyAccess",            config_parse_notify_access,         0,                             offsetof(Service, notify_access)},
      {"Swap.LimitNOFILE",                  config_parse_limit,                 RLIMIT_NOFILE,                 offsetof(Swap, exec_context.rlimit)},
      {(char*)0},
      {"Service.FsckPassNo",              config_parse_fsck_passno,           0,                             offsetof(Service, fsck_passno)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"Mount.LimitRTTIME",                  config_parse_limit,                 RLIMIT_RTTIME,                 offsetof(Mount, exec_context.rlimit)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"Service.WorkingDirectory",            config_parse_unit_path_printf,      0,                             offsetof(Service, exec_context.working_directory)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"Service.TTYPath",                      config_parse_unit_path_printf,      0,                             offsetof(Service, exec_context.tty_path)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Socket.BlockIOWriteBandwidth",        config_parse_unit_cgroup_attr_pretty, 0,                           0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"Mount.CPUSchedulingResetOnFork",     config_parse_bool,                  0,                             offsetof(Mount, exec_context.cpu_sched_reset_on_fork)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Mount.LimitMSGQUEUE",                config_parse_limit,                 RLIMIT_MSGQUEUE,               offsetof(Mount, exec_context.rlimit)},
      {(char*)0},
      {"Swap.LimitRTTIME",                  config_parse_limit,                 RLIMIT_RTTIME,                 offsetof(Swap, exec_context.rlimit)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"Mount.LimitRTPRIO",                  config_parse_limit,                 RLIMIT_RTPRIO,                 offsetof(Mount, exec_context.rlimit)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Mount.LimitCORE",                    config_parse_limit,                 RLIMIT_CORE,                   offsetof(Mount, exec_context.rlimit)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"Mount.LimitFSIZE",                   config_parse_limit,                 RLIMIT_FSIZE,                  offsetof(Mount, exec_context.rlimit)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Mount.LimitMEMLOCK",                 config_parse_limit,                 RLIMIT_MEMLOCK,                offsetof(Mount, exec_context.rlimit)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"Service.LimitDATA",                    config_parse_limit,                 RLIMIT_DATA,                   offsetof(Service, exec_context.rlimit)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"Mount.LimitNOFILE",                  config_parse_limit,                 RLIMIT_NOFILE,                 offsetof(Mount, exec_context.rlimit)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Mount.LimitNPROC",                   config_parse_limit,                 RLIMIT_NPROC,                  offsetof(Mount, exec_context.rlimit)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"Socket.UMask",                        config_parse_mode,                  0,                             offsetof(Socket, exec_context.umask)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"Mount.LimitNICE",                    config_parse_limit,                 RLIMIT_NICE,                   offsetof(Mount, exec_context.rlimit)},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"Mount.LimitDATA",                    config_parse_limit,                 RLIMIT_DATA,                   offsetof(Mount, exec_context.rlimit)}
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = load_fragment_gperf_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        {
          register const char *s = wordlist[key].section_and_lvalue;

          if (s && *str == *s && !strcmp (str + 1, s + 1))
            return &wordlist[key];
        }
    }
  return 0;
}
